### ISSUE TITLE
Ci/Cd sample - manifest deprecation checking

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#481]
Add [Pluto ](https://github.com/FairwindsOps/pluto#github-action-usage) into the GitHub action workflow for app smoke tests (Azure voting app) to show deprecated api versions in manifests/helm charts.

```yml
- name: Download Pluto
  uses: FairwindsOps/pluto/github-action@master

- name: Use pluto
  run: |
    pluto detect-files -d pkg/finder/testdata
```

We can add this into the [AppDeploy_AzureVote.yml](https://github.com/Azure/AKS-Construction/blob/main/.github/workflows/AppDeploy_AzureVote.yml) for app install, and reference it in the `samples/workflows/readme.md`
