### ISSUE TITLE
Optimise infra CI/CD during PR

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#506]
We need to refine the triggers/conditions when using these labels on a PR that is marked as draft. Currently during a typical PR cycle that uses these labels we're seeing excessive queueing of builds that take a lot of time.
Full infra deployment tests will run on draft PR's with these labels.
![image](https://user-images.githubusercontent.com/17914476/214945077-46138afb-6c0f-4922-b944-b3cc689f435f.png)

We need to use type filtering and step conditons to ensure they are only run when the PR is in the `right state` and is `ready for review`

```yaml
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
```
