### ISSUE TITLE
Helper: Sample GitHub workflow missing permissions

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#522]
When following the instructions to use AKSC to create a GitHub workflow i experience this error.

![image](https://user-images.githubusercontent.com/17914476/217799562-389168a8-5216-4850-97aa-8bf04d15c19a.png)

I need to add this permissions block in order for the workflow to run successfully

```yml
permissions:
      id-token: write
      contents: read
```

![image](https://user-images.githubusercontent.com/17914476/217799908-406e2fcd-a3c3-4b12-af9c-88da0c536a44.png)
