### ISSUE TITLE
Can't find a way to enable Cilium?

### ISSUE THREAD

**Issue by Jaykul** [Azure/AKS-Construction#535]
When I selected Cilium, my script comes out with `ebpfDataplane=cilium` but I'm getting this error:

```
"code":"BadRequest",
"message": {
  "code": "BadRequest",
  "message": "Cilium dataplane requires network policy cilium.",
  "subcode": "CiliumDataplaneRequiresNetworkPolicyCilium",
  "target": "networkProfile.networkPolicy"
}
```
But I'm pretty sure that's not possible 😉 because networkPolicy can only be "azure" or "calico"

To reproduce, use the workflow like this (except I redacted the authorizedIPRanges):

```
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.9.10
    with:
      templateVersion: 0.9.10
      templateParams: resourceName=aks-poshcode agentCount=0 upgradeChannel=stable agentCountMax=3 custom_vnet=true vnetAksSubnetAddressPrefix=10.240.0.0/24 bastion=true enable_aad=true AksDisableLocalAccounts=true enableAzureRBAC=true adminPrincipalId=_USER_OBJECT_ID_ networkPolicy=cilium openServiceMeshAddon=true azurepolicy=audit authorizedIPRanges=["127.0.0.1"] maxPods=40 keyVaultKmsCreate=true keyVaultKmsOfficerRolePrincipalId=_USER_OBJECT_ID_ fluxGitOpsAddon=true createNatGateway=true aksOutboundTrafficType=userAssignedNATGateway natGwIdleTimeout=20 kedaAddon=true blobCSIDriver=true oidcIssuer=true workloadIdentity=true networkPluginMode=Overlay ebpfDataplane=cilium
      postScriptParams: "ingress=contour,monitor=oss"
```
